// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/bank/bank.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBankAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankId        uint64                 `protobuf:"varint,1,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankAccountRequest) Reset() {
	*x = GetBankAccountRequest{}
	mi := &file_proto_bank_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankAccountRequest) ProtoMessage() {}

func (x *GetBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankAccountRequest.ProtoReflect.Descriptor instead.
func (*GetBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_bank_proto_rawDescGZIP(), []int{0}
}

func (x *GetBankAccountRequest) GetBankId() uint64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *GetBankAccountRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBankAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankAccountResponse) Reset() {
	*x = GetBankAccountResponse{}
	mi := &file_proto_bank_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankAccountResponse) ProtoMessage() {}

func (x *GetBankAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankAccountResponse.ProtoReflect.Descriptor instead.
func (*GetBankAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_bank_proto_rawDescGZIP(), []int{1}
}

func (x *GetBankAccountResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBankAccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBankAccountResponse) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

var File_proto_bank_bank_proto protoreflect.FileDescriptor

const file_proto_bank_bank_proto_rawDesc = "" +
	"\n" +
	"\x15proto/bank/bank.proto\x12\x04bank\"I\n" +
	"\x15GetBankAccountRequest\x12\x17\n" +
	"\abank_id\x18\x01 \x01(\x04R\x06bankId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"a\n" +
	"\x16GetBankAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName2Z\n" +
	"\vBankService\x12K\n" +
	"\x0eGetBankAccount\x12\x1b.bank.GetBankAccountRequest\x1a\x1c.bank.GetBankAccountResponseB5Z3github.com/dotenv213/aim/account-service/proto/bankb\x06proto3"

var (
	file_proto_bank_bank_proto_rawDescOnce sync.Once
	file_proto_bank_bank_proto_rawDescData []byte
)

func file_proto_bank_bank_proto_rawDescGZIP() []byte {
	file_proto_bank_bank_proto_rawDescOnce.Do(func() {
		file_proto_bank_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_bank_proto_rawDesc), len(file_proto_bank_bank_proto_rawDesc)))
	})
	return file_proto_bank_bank_proto_rawDescData
}

var file_proto_bank_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_bank_proto_goTypes = []any{
	(*GetBankAccountRequest)(nil),  // 0: bank.GetBankAccountRequest
	(*GetBankAccountResponse)(nil), // 1: bank.GetBankAccountResponse
}
var file_proto_bank_bank_proto_depIdxs = []int32{
	0, // 0: bank.BankService.GetBankAccount:input_type -> bank.GetBankAccountRequest
	1, // 1: bank.BankService.GetBankAccount:output_type -> bank.GetBankAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_bank_proto_init() }
func file_proto_bank_bank_proto_init() {
	if File_proto_bank_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_bank_proto_rawDesc), len(file_proto_bank_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bank_bank_proto_goTypes,
		DependencyIndexes: file_proto_bank_bank_proto_depIdxs,
		MessageInfos:      file_proto_bank_bank_proto_msgTypes,
	}.Build()
	File_proto_bank_bank_proto = out.File
	file_proto_bank_bank_proto_goTypes = nil
	file_proto_bank_bank_proto_depIdxs = nil
}
